#!/bin/sh

# OTC_URL is e.g. "http://localhost:8810/"
# OTC_KEY is e.g. "secret"

[ -z "$OTC_URL" ] && { echo "$0: needs OTC_URL in environment" >&2; exit 1; }
[ -z "$OTC_KEY" ] && { echo "$0: needs OTC_KEY in environment" >&2; exit 1; }

[ $# -ne 1 ] && { echo "Usage: $0 jarFile" >&2; exit 2; }
jarfile="$1"

[ -f "$jarfile" ] || { echo "Can't open file $jarfile" >&2; exit 1; }

HASH=$(/bin/echo -n "$OTC_KEY"  | shasum -a 256 | awk '{print $1;}')

curl -F otckey="${HASH}" -F jar=@"${jarfile}"  "${OTC_URL}/jarupload"
